//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int Quantity { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual Product Product { get; set; }
    }
}
