//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Name { get; set; }
        public string Auth { get; set; }
        public int Price { get; set; }
        public int Id { get; set; }
    }
}
